services:
    start:
        build: .
        environment:
            API_ID: $API_ID
            API_HASH: $API_HASH
            BOT_TOKEN: $BOT_TOKEN
            DATABASE_URL: $DATABASE_URL
            CHECK_INTERVAL: $CHECK_INTERVAL
            MAX_INSTANCES: $MAX_INSTANCES
